// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEaa7cc45DecodeGithubComMastermengGowebModels(in *jlexer.Lexer, out *Atricles) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "abstract":
			out.Abstract = string(in.String())
		case "createdate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreateDate).UnmarshalJSON(data))
			}
		case "moditydate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ModityDate).UnmarshalJSON(data))
			}
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEaa7cc45EncodeGithubComMastermengGowebModels(out *jwriter.Writer, in Atricles) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"abstract\":"
		out.RawString(prefix)
		out.String(string(in.Abstract))
	}
	{
		const prefix string = ",\"createdate\":"
		out.RawString(prefix)
		out.Raw((in.CreateDate).MarshalJSON())
	}
	{
		const prefix string = ",\"moditydate\":"
		out.RawString(prefix)
		out.Raw((in.ModityDate).MarshalJSON())
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Atricles) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEaa7cc45EncodeGithubComMastermengGowebModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Atricles) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEaa7cc45EncodeGithubComMastermengGowebModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Atricles) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEaa7cc45DecodeGithubComMastermengGowebModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Atricles) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEaa7cc45DecodeGithubComMastermengGowebModels(l, v)
}
